# Generated by Django 5.2.17 on 2026-08-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_aircraft_alter_airline_id_alter_airport_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='aircraft',
        ),
    ]
