# Generated by Django 5.2.17 on 2026-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_segment_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
