# Generated by Django 5.2.17 on 2026-08-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airport_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
