# Generated by Django 5.2.17 on 2026-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_airline_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline_data',
            name='region_acceptable',
            field=models.BooleanField(default=False),
        ),
    ]
